### ISSUE TITLE
BUG Fix joblib dependency in sklearn

### ISSUE THREAD

**Issue by PSSF23** [neurodata/honest-forests#5]
@sampan501 Can you share the commented-out lines here?

**Comment by rflperry** [comment]
The open pull request #4  has a fix, it was just missing an update to the requirements.txt file I believe.

**Comment by PSSF23** [comment]
@rflperry I don't think the author of #4 is still contributing. Should we separate the fix into another PR?

**Comment by rflperry** [comment]
@PSSF23 Yeah, something like that should be two PRs anyways. I was just saying the needed code modifications/discussion (in theory) are in that PR.

**Comment by PSSF23** [comment]
Surely, I will try to apply the fix then.
